//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BluffinMuffin.Logger.DBAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BluffinMuffinLogsEntities : DbContext
    {
        public BluffinMuffinLogsEntities()
            : base("name=BluffinMuffinLogsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ClientEntity> AllClients { get; set; }
        public virtual DbSet<CommandEntity> AllCommands { get; set; }
        public virtual DbSet<BlindTypeEntity> AllBlindTypes { get; set; }
        public virtual DbSet<GameSubTypeEntity> AllGameSubTypes { get; set; }
        public virtual DbSet<GameTypeEntity> AllGameTypes { get; set; }
        public virtual DbSet<LimitTypeEntity> AllLimitTypes { get; set; }
        public virtual DbSet<LobbyTypeEntity> AllLobbyTypes { get; set; }
        public virtual DbSet<GameEntity> AllGames { get; set; }
        public virtual DbSet<ServerEntity> AllServers { get; set; }
        public virtual DbSet<TableParamEntity> AllTableParams { get; set; }
    }
}
