//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BluffinMuffin.Logger.DBAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Command
    {
        public int Id { get; set; }
        public System.DateTime ExecutionTime { get; set; }
        public string Name { get; set; }
        public bool IsFromServer { get; set; }
        public int ServerId { get; set; }
        public int ClientId { get; set; }
        public string Type { get; set; }
        public Nullable<int> GameId { get; set; }
        public string Detail { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Game Game { get; set; }
        public virtual Server Server { get; set; }
    }
}
