//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BluffinMuffin.Logger.DBAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BluffinMuffinLogsEntities : DbContext
    {
        public BluffinMuffinLogsEntities()
            : base("name=BluffinMuffinLogsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Command> Commands { get; set; }
        public virtual DbSet<CtlBlindType> CtlBlindTypes { get; set; }
        public virtual DbSet<CtlGameSubType> CtlGameSubTypes { get; set; }
        public virtual DbSet<CtlGameType> CtlGameTypes { get; set; }
        public virtual DbSet<CtlLimitType> CtlLimitTypes { get; set; }
        public virtual DbSet<CtlLobbyType> CtlLobbyTypes { get; set; }
        public virtual DbSet<Game> Games { get; set; }
        public virtual DbSet<Server> Servers { get; set; }
        public virtual DbSet<TableParam> TableParams { get; set; }
    }
}
