//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BluffinMuffin.Logger.DBAccess
{
    using System;
    using System.Collections.Generic;
    
    internal partial class ServerEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServerEntity()
        {
            this.CommandsOfServer = new HashSet<CommandEntity>();
            this.TableParamsOfServer = new HashSet<TableParamEntity>();
        }
    
        public int Id { get; set; }
        public string ServerIdentification { get; set; }
        public string ImplementedProtocol { get; set; }
        public System.DateTime ServerStartedAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        internal virtual ICollection<CommandEntity> CommandsOfServer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        internal virtual ICollection<TableParamEntity> TableParamsOfServer { get; set; }
    }
}
