//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BluffinMuffin.Logger.DBAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableParam
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TableParam()
        {
            this.GamesOfTableParam = new HashSet<Game>();
        }
    
        public int Id { get; set; }
        public string TableName { get; set; }
        public int GameSubTypeId { get; set; }
        public int MinPlayerToStart { get; set; }
        public int MaxPlayer { get; set; }
        public string Arguments { get; set; }
        public int LobbyTypeId { get; set; }
        public int BlindTypeId { get; set; }
        public int LimitTypeId { get; set; }
        public int ServerId { get; set; }
        public System.DateTime TableStartedAt { get; set; }
    
        public virtual CtlBlindType BlindType { get; set; }
        public virtual CtlGameSubType GameSubType { get; set; }
        public virtual CtlLimitType LimitType { get; set; }
        public virtual CtlLobbyType LobbyType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Game> GamesOfTableParam { get; set; }
        public virtual Server Server { get; set; }
    }
}
