//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BluffinMuffin.Logger.DBAccess
{
    using System;
    using System.Collections.Generic;
    
    internal partial class TableParamEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TableParamEntity()
        {
            this.GamesUsingTableParam = new HashSet<GameEntity>();
        }
    
        public int Id { get; set; }
        public string TableName { get; set; }
        public int GameSubTypeId { get; set; }
        public int MinPlayerToStart { get; set; }
        public int MaxPlayer { get; set; }
        public string Arguments { get; set; }
        public int LobbyTypeId { get; set; }
        public int BlindTypeId { get; set; }
        public int LimitTypeId { get; set; }
        public int ServerId { get; set; }
        public System.DateTime TableStartedAt { get; set; }
    
        internal virtual BlindTypeEntity BlindType { get; set; }
        internal virtual GameSubTypeEntity GameSubType { get; set; }
        internal virtual LimitTypeEntity LimitType { get; set; }
        internal virtual LobbyTypeEntity LobbyType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        internal virtual ICollection<GameEntity> GamesUsingTableParam { get; set; }
        internal virtual ServerEntity Server { get; set; }
    }
}
